const rows=[
["CS1001","Payment","Email","Service Desk","High","Resolved",1.2,8.5,"Yes"],["CS1002","Account","Chat","Service Desk","Medium","Resolved",0.6,4.1,"Yes"],["CS1003","Technical","Web","Applications","High","Resolved",2.4,12.8,"No"],["CS1004","Access","Email","Access","Medium","Resolved",1,5.3,"Yes"],["CS1005","Payment","Chat","Service Desk","Critical","Resolved",0.3,3.9,"Yes"],["CS1006","Technical","Web","Applications","Medium","Pending",3.1,0,"Yes"],["CS1007","Account","Email","Service Desk","Low","Resolved",2,6.2,"Yes"],["CS1008","Payment","Web","Service Desk","High","Resolved",1.7,10.4,"Yes"],["CS1009","Access","Chat","Access","High","Resolved",0.8,7.2,"Yes"],["CS1010","Technical","Email","Applications","Critical","Resolved",2.9,18.5,"No"],["CS1011","Payment","Chat","Service Desk","Medium","Open",1.4,0,"Yes"],["CS1012","Account","Web","Service Desk","Low","Resolved",2.6,7.8,"Yes"],["CS1013","Technical","Email","Applications","High","Resolved",1.9,11.3,"No"],["CS1014","Access","Chat","Access","Medium","Resolved",0.7,4.8,"Yes"],["CS1015","Payment","Email","Service Desk","High","Resolved",1.1,9.1,"Yes"],["CS1016","Account","Chat","Service Desk","Medium","Resolved",0.9,5.6,"Yes"],["CS1017","Technical","Web","Applications","High","Pending",2.2,0,"Yes"],["CS1018","Payment","Email","Service Desk","Critical","Resolved",0.4,5.2,"Yes"],["CS1019","Access","Web","Access","Low","Resolved",1.8,6.7,"Yes"],["CS1020","Technical","Email","Applications","Medium","Resolved",2.5,9.8,"Yes"],["CS1021","Payment","Chat","Service Desk","High","Resolved",1.3,8.7,"Yes"],["CS1022","Account","Email","Service Desk","Low","Resolved",1.6,5.9,"Yes"],["CS1023","Technical","Web","Applications","Critical","Resolved",3.4,20.1,"No"],["CS1024","Access","Chat","Access","Medium","Open",1,0,"Yes"],["CS1025","Payment","Email","Service Desk","Medium","Resolved",1,6.4,"Yes"],["CS1026","Account","Web","Service Desk","High","Resolved",1.2,8.2,"Yes"],["CS1027","Technical","Email","Applications","High","Resolved",2.1,13.4,"No"],["CS1028","Access","Chat","Access","Low","Resolved",1.5,5.1,"Yes"],["CS1029","Payment","Web","Service Desk","Critical","Resolved",0.5,4.6,"Yes"],["CS1030","Account","Email","Service Desk","Medium","Pending",2,0,"Yes"]
].map(r=>({id:r[0],category:r[1],channel:r[2],team:r[3],priority:r[4],status:r[5],response:r[6],resolution:r[7],sla:r[8]}));
const $=id=>document.getElementById(id);
function filtered(){return rows.filter(r=>(($("category").value==="All")||r.category===$("category").value)&&(($("priority").value==="All")||r.priority===$("priority").value)&&(($("status").value==="All")||r.status===$("status").value))}
function render(){const d=filtered(), resolved=d.filter(r=>r.status==="Resolved"), sla=d.filter(r=>r.sla==="Yes").length; $("total").textContent=d.length;$("sla").textContent=d.length?Math.round(sla/d.length*100)+"%":"0%";$("response").textContent=d.length?(d.reduce((a,r)=>a+r.response,0)/d.length).toFixed(1)+"h":"0h";$("resolution").textContent=resolved.length?(resolved.reduce((a,r)=>a+r.resolution,0)/resolved.length).toFixed(1)+"h":"0h";
const counts={};d.forEach(r=>counts[r.category]=(counts[r.category]||0)+1);const max=Math.max(1,...Object.values(counts));$("bars").innerHTML=Object.entries(counts).map(([k,v])=>'<div class="bar"><label><span>'+k+'</span><b>'+v+'</b></label><div class="track"><div class="fill" style="width:'+v/max*100+'%"></div></div></div>').join("");
const cats=Object.entries(counts).sort((a,b)=>b[1]-a[1]);$("insights").innerHTML=d.length?'<li>'+cats[0][0]+' is the highest-volume category in the filtered sample.</li><li>'+sla+' of '+d.length+' cases meet the sample SLA target.</li><li>'+resolved.length+' cases are resolved; unresolved cases remain visible for operational follow-up.</li>':'<li>No cases match the selected filters.</li>';
$("rows").innerHTML=d.slice(0,20).map(r=>'<tr><td>'+r.id+'</td><td>'+r.category+'</td><td>'+r.channel+'</td><td>'+r.team+'</td><td>'+r.priority+'</td><td>'+r.status+'</td><td>'+r.sla+'</td></tr>').join("")}
["category","priority","status"].forEach(id=>$(id).addEventListener("change",render));$("reset").addEventListener("click",()=>{["category","priority","status"].forEach(id=>$(id).value="All");render()});render();
